### PR TITLE
Fix Kuiper test

### PR DESCRIPTION
**Pull request by Azhag**
Heya!

Was trying to get Kuiper 2 sample test going, and saw a few mistakes which I fixed:

- Setup.py wasn't installing kuiper_table.npy
- _kuiper_lookup wasn't converted from Matlab properly, you had an off by one error that triggered for N>501.

Thanks for the package, really useful!

cheers
Loic

### CODE REVIEW

**Comment by fabiansinz** [comment]
Hey Loic, 

thanks for contributing. We haven't had a pull request in a while and we need to update our `.travis.yml` for automated testing. Once that is fixed, I will ask you to update your pull request. Thanks!

Fabian

**Comment by fabiansinz** [comment]
Can you merge the latest updates and update you pull request? We fixed the travis file.

**Comment by Azhag** [comment]
Done!
But I didn't check the unit tests and they fail now, I'll have a look and see if I introduced a bug.

**Comment by fabiansinz** [comment]
That'd be great. Thank you.

**Comment by Azhag** [comment]
Ok fixed it, actually your test was wrong, which my commit fixed :P 

Made a correct test now, with an N that really isn't in the Kuiper Table.

Added a test to make sure that results with angles in [0, 2pi] work in [-pi, pi], as I wasn't sure if the library supported it :)

**Comment by fabiansinz** [comment]
Thank you!

**Pull request merged**
